---
title: "CaliBombus Spatial"
output:
  html_document: default
  pdf_document: default
---

#Load Packages
```{r, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(sf)
library(tmap)
library(sp)
library(spatialEco)
library(rgdal)
library(stringr)


```

#Import data from EPA/USGS and CaliBombus
## Note: USGS is in a projected coordinate system and GPS coordinates are in a geographic coordinate system 

I used the sf package
Also changed NA_L3Names so they are shorter 
```{r, include=FALSE}
#Import ecoregion shape file from EPA/USGS Level III 
ecoregionshape<-st_read("./USGS_ecoregions20/ca_eco_l3.shp") #sf package
#Check coordinate reference system 
st_crs(ecoregionshape) #sf package
# Coordinate reference system is USA_Contiguous_Albers_Equal_Area_Conic_USGS_version
# Datum is North American Datum 1983

##Recode variable names so they are shorter 
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Coast Range' = "Coast Range")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Central Basin and Range' = "Central Basin")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Mojave Basin and Range' = "Mojave Basin")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Sierra Nevada' = "Sierra Nevada")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'California Coastal Sage, Chaparral, and Oak Woodlands' = "Coastal Sage")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Central California Valley' = "Central Valley")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Klamath Mountains' = "Klamath")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Southern and Baja California Pine-Oak Mountains' = "SoCal Mountains")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Northern Basin and Range' = "Northern Basin")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Sonoran Desert' = "Sonoran Desert")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Eastern Cascades Slopes and Foothills' = "Eastern Cascades")

#Condense ecoregion to name and geometry (ie. coordinates)
ecoregions<-ecoregionshape %>% select(NA_L3NAME, geometry)


#Read in site gps coordinates
site<-read.csv("./USGS_ecoregions20/spatialinfofinal.csv") %>% select(Site_Grouping, lon, lat) 

# Make sites into a spatial object
cordSites<-st_as_sf(site, 
                        coords = c("lon", "lat"),
                        crs = st_crs("+proj=longlat"))

#Convert lat/long data to same projection as USGS Ecoregions
sites_Cali19<-st_transform(cordSites, crs=st_crs(ecoregionshape)) %>% rename(site= Site_Grouping)

#Overlay gps points with ecoregion polygons to see which sites are in which ecoregions
Calibombussites_ecoregions<-point.in.poly(sites_Cali19, ecoregions) %>% as.data.frame()
write.csv(Calibombussites_ecoregions, "./DataFrames/calibombussites_ecoregion.csv")
```
#Make a pretty map 
```{r}
#Map without labels
tm_shape(ecoregions) + tm_style("col_blind")+
  tm_polygons(col="NA_L3NAME", border.col="white", palette="Dark2", title="Ecoregion")+
  tm_shape(sites_Cali19) + tm_dots(size=0.2, col="black")+
 tm_layout(frame=FALSE, legend.text.size=0.7, legend.width=1)+tm_legend(legend.position=c("right", "top"), outside=TRUE) 
```










