---
title: "California Pre-1983 Comparison with Contemporary Data"
output: html_document
---
## Load Packages
```{r}
library(iNEXT)
library(ggplot2)
library(dplyr)
```

# General Comparison Numbers
```{r}
print(paste("There are", nrow(dataFINAL), "observations in the calibombus dataset"))
print(paste("We have", nrow(thirtyfifty), "datapoints between 1930 and 1959"))
print(paste("We have", nrow(sixtyeighty), "datapoints between 1960 and 1989"))
print(paste("We have", nrow(twothous), "datapoints between 1990 and 2019"))
print(paste("We have", nrow(Pre83_ecoregions), "datapoints before or in 1983"))

```

# 1983 Patterns 
```{r}
datapre83<-Pre83_ecoregions %>% rename(Ecoregion=NA_L3NAME)
nrow(datapre83)

CaliPre83<-datapre83 %>% mutate(count=1) %>% group_by(Ecoregion, species) %>% mutate(specieseco=sum(count)) %>% select(species, Ecoregion, specieseco) %>% unique()

robinorder<-c("nevadensis", "griseocollis", "morrisoni", "crotchii", "rufocintus", 
              "appositus", 
              "californicus",
              "fervidus", 
              "sonorus",
              "franklini", 
              "occidentalis", 
              "bifarius",
              "caliginosus", 
              "centralis",
              "edwardsii", 
              "flavifrons", 
              "huntii", 
              "melanopygus", 
              "mixtus", 
              "sitkensis", 
              "sylvicola",
              "vandykei",
              "vosnesenskii",
              "balteatus",
              "suckleyi",
              "insularis",
              "fernaldae")

##Make dataframe so that order of species is like robins 
CaliRobinOrder<-CaliPre83 %>% pivot_wider(names_from=Ecoregion, values_from=specieseco) %>% mutate(species=factor(species, levels=robinorder)) %>% mutate_all(~replace(., is.na(.), 0)) %>%  na.omit()
write.csv(CaliRobinOrder, "CaliforniaPre1983.csv", row.names=FALSE )

#Make dataframe to use in iNEXT 
#species abundance needs to be integer, species needs to be a character
CaliPre83$specieseco<-as.integer(CaliPre83$specieseco)
CaliPre83
nextbohart<- CaliPre83 %>% pivot_wider(names_from=Ecoregion, values_from=specieseco) 
nextbohart$species<-as.character(nextbohart$species)
nextbohart2<-nextbohart %>% replace(is.na(.), 0) %>% column_to_rownames(var="species") %>% select(!'NA')
nextbohart2 
```
## Species Richness using iNEXT for 1983 data
```{r}
#Species Richness, Hill Number 1

str(nextbohart2)
#Species Richness, Hill Number 1
out<-iNEXT(nextbohart2 , q=c(1), datatype="abundance", endpoint=1000)

ggiNEXT(out, type=1) + 
  theme_bw(base_size=10)+
  guides(shapetype=FALSE)+ 
  theme(legend.position = "right",legend.title=element_blank(),text=element_text(size=8),
        plot.title=element_text(size=10), legend.key.size = unit(0.5, "cm"), legend.key.width = unit(0.05,"cm")) + ggtitle("Historical Data")+ylim(0,9)+geom_line(size = .3)

out 
ggiNEXT(out, type=1) + theme_bw(base_size=10) + guides(linetype=FALSE)

#Make dataframe using estimations from iNEXT - "HistoricaliNEXT.csv"
# Copied and pasted from results, could not make iNEXT results into dataframe
```

### Estimated species richness comparisons between historical (pre-1983) and contemporary (2019) using iNEXT estimations 
```{r}
#Read in historical data (California pre-1983)
historical83<-read.csv("./HistoricaliNEXT.csv")
head(historical83)
histcomp<-historical83 %>% select(Site, Diversity, Estimator) %>% filter(Diversity=="Species richness") %>%
  rename('Estimated Richness' = Estimator) %>% select(!Diversity) %>% mutate(timepoint="historical")
histcomp
histcomp$`Estimated Richness`<-as.integer(histcomp$`Estimated Richness`)
histcomp



#Read in Calibombus data - contemporary 
contemp19<-read.csv("./ContemporaryiNEXT.csv")
contempcomp<-contemp19 %>% select(Site, Diversity, Estimator) %>% filter(Diversity=="Species richness") %>% rename('Estimated Richness' = Estimator) %>% select(!Diversity) %>% mutate(timepoint="contemporary")
contempcomp$`Estimated Richness`<-as.integer(contempcomp$`Estimated Richness`)
contempcomp

#Merge two data frames together so there are only sites that are shared between both timepoints
combinedcomp<-rbind(histcomp, contempcomp)
combinedcomp

ggplot(combinedcomp, aes(x=Site, y=`Estimated Richness`, fill=timepoint)) +geom_bar(stat="identity", position=position_dodge())+xlab("Ecoregion")+ylab("Estimated Richness")+theme(axis.text.x=element_text(angle=90))


```
# Binned years and get iNEXT data for each bin group 
```{r}
# 1930-1959
THIRTYFIFTY<-thirtyfifty %>% mutate(count=1) %>% group_by(Ecoregion, species) %>% mutate(specieseco=sum(count)) %>% select(species, Ecoregion, specieseco) %>% unique()
THIRTYFIFTY$specieseco<-as.integer(THIRTYFIFTY$specieseco)
next35<- THIRTYFIFTY %>% pivot_wider(names_from=Ecoregion, values_from=specieseco) 
next35$species<-as.character(next35$species)
next35final<-next35 %>% replace(is.na(.), 0) %>% column_to_rownames(var="species") %>% select(!'NA')

str(next35final)
#iNEXT 
out<-iNEXT(next35final, q=c(1), datatype="abundance", endpoint=1000)
ggiNEXT(out, type=1) + 
  theme_bw(base_size=10)+
  guides(shapetype=FALSE)+ 
  theme(legend.position = "right",legend.title=element_blank(),text=element_text(size=8),
        plot.title=element_text(size=10), legend.key.size = unit(0.5, "cm"), legend.key.width = unit(0.05,"cm")) + ggtitle("Historical Data")+ylim(0,9)+geom_line(size = .3)
out 
######################################################################################################

# 1960-1989
SIXTYEIGHTY<-sixtyeighty %>% mutate(count=1) %>% group_by(Ecoregion, species) %>% mutate(specieseco=sum(count)) %>% select(species, Ecoregion, specieseco) %>% unique()
SIXTYEIGHTY$specieseco<-as.integer(SIXTYEIGHTY$specieseco)
next68<- SIXTYEIGHTY %>% pivot_wider(names_from=Ecoregion, values_from=specieseco) 
next68$species<-as.character(next68$species)
next68final<-next68 %>% replace(is.na(.), 0) %>% column_to_rownames(var="species") %>% select(!'NA')

str(next68final)
#iNEXT 
out<-iNEXT(next68final, q=c(1), datatype="abundance", endpoint=1000)
ggiNEXT(out, type=1) + 
  theme_bw(base_size=10)+
  guides(shapetype=FALSE)+ 
  theme(legend.position = "right",legend.title=element_blank(),text=element_text(size=8),
        plot.title=element_text(size=10), legend.key.size = unit(0.5, "cm"), legend.key.width = unit(0.05,"cm")) + ggtitle("Historical Data")+ylim(0,9)+geom_line(size = .3)
out 

######################################################################################################
# 2000-2019
TWOTHOUS<-twothous %>% mutate(count=1) %>% group_by(Ecoregion, species) %>% mutate(specieseco=sum(count)) %>% select(species, Ecoregion, specieseco) %>% unique()
TWOTHOUS$specieseco<-as.integer(TWOTHOUS$specieseco)
next29<- TWOTHOUS %>% pivot_wider(names_from=Ecoregion, values_from=specieseco) 
next29$species<-as.character(next29$species)
next29final<-next29 %>% replace(is.na(.), 0) %>% column_to_rownames(var="species") %>% select(!'NA')

str(next29final)
#iNEXT 
out<-iNEXT(next29final, q=c(1), datatype="abundance", endpoint=1000)
ggiNEXT(out, type=1) + 
  theme_bw(base_size=10)+
  guides(shapetype=FALSE)+ 
  theme(legend.position = "right",legend.title=element_blank(),text=element_text(size=8),
        plot.title=element_text(size=10), legend.key.size = unit(0.5, "cm"), legend.key.width = unit(0.05,"cm")) + ggtitle("Historical Data")+ylim(0,9)+geom_line(size = .3)
out 

```

```{r}
ThirtyFifty<-read.csv("./ThirtyFifty.csv")
CONTEMP35<-ThirtyFifty %>% select(Site, Diversity, Estimator) %>% filter(Diversity=="Species richness") %>% rename('Estimated Richness' = Estimator) %>% select(!Diversity) %>% mutate(timepoint="1930-1959")
CONTEMP35$`Estimated Richness`<-as.integer(CONTEMP35$`Estimated Richness`)
CONTEMP35

SixtyEighty<-read.csv("./SixtyEighty.csv")
CONTEMP68<-SixtyEighty %>% select(Site, Diversity, Estimator) %>% filter(Diversity=="Species richness") %>% rename('Estimated Richness' = Estimator) %>% select(!Diversity) %>% mutate(timepoint="1960-1989")
CONTEMP68$`Estimated Richness`<-as.integer(CONTEMP68$`Estimated Richness`)
CONTEMP68

TwoThous<-read.csv("./TwoThous.csv")
CONTEMP20<-TwoThous %>% select(Site, Diversity, Estimator) %>% filter(Diversity=="Species richness") %>% rename('Estimated Richness' = Estimator) %>% select(!Diversity) %>% mutate(timepoint="1990-2019")
CONTEMP20$`Estimated Richness`<-as.integer(CONTEMP20$`Estimated Richness`)
CONTEMP20


#Merge two data frames together so there are only sites that are shared between both timepoints
combinedchunks<-rbind(CONTEMP35, CONTEMP68, CONTEMP20, contempcomp)
combinedchunks

ggplot(combinedchunks, aes(x=Site, y=`Estimated Richness`, fill=timepoint)) +geom_bar(stat="identity", position=position_dodge())+xlab("Ecoregion")+ylab("Estimated Richness")+theme(axis.text.x=element_text(angle=90))

```















#NMDS comparisons between historical and contemproary datasets 
```{r}
#Remove first two rows - no species name 
prep<-CaliPre83 %>% arrange(species) 
prepf<- prep[3:nrow(prep),] %>% mutate(timepoint="historical")


#Transform into dataframe with species as column and ecoregion as rows
prepf2<-prepf %>% pivot_wider(names_from=species, values_from=specieseco) %>% filter(Ecoregion != "NA") %>%
  replace(is.na(.), 0) 
prepf2

nextbohart2<-nextbohart %>% replace(is.na(.), 0) %>% column_to_rownames(var="species") %>% select(!'NA')
nextbohart2 


```


