---
title: "Postdoc Maps"
output: pdf_document
---
```{r, include=FALSE}
library(dplyr)
library(ggplot2)
library(tidyr)
library(sf)
library(tmap)
library(sp)
library(spatialEco)
library(rgdal)
library(stringr)


```

## NIFA MAP 
```{r}

#Import ecoregion shape file from EPA/USGS Level III 
ecoregionshape<-st_read("../USGS_ecoregions20/ca_eco_l3.shp") #sf package
#Check coordinate reference system 
st_crs(ecoregionshape) #sf package
# Coordinate reference system is USA_Contiguous_Albers_Equal_Area_Conic_USGS_version
# Datum is North American Datum 1983

##Recode variable names so they are shorter 
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Coast Range' = "Coast Range")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Central Basin and Range' = "Central Basin")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Mojave Basin and Range' = "Mojave Basin Range")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Sierra Nevada' = "Sierra Nevada")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'California Coastal Sage, Chaparral, and Oak Woodlands' = "Coastal Sage")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Central California Valley' = "Central California Valley")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Klamath Mountains' = "Klamath")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Southern and Baja California Pine-Oak Mountains' = "Southern California Mountains")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Northern Basin and Range' = "Northern Basin")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Sonoran Desert' = "Sonoran Desert")
ecoregionshape$NA_L3NAME<-recode(ecoregionshape$NA_L3NAME, 'Eastern Cascades Slopes and Foothills' = "Eastern Cascades")

#Condense ecoregion to name and geometry (ie. coordinates)
ecoregions<-ecoregionshape %>% select(NA_L3NAME, geometry)

## Import calibombus sites
site<-read.csv("../USGS_ecoregions20/spatialinfofinal.csv") %>% select(Site_Grouping, lon, lat) %>% mutate(sampled="2019") %>% rename(Site=Site_Grouping)

#Import new NIFA sites 
TwentyTwentysites<-read.csv("../PostDocStuff/NIFASites.csv") %>% mutate(sampled="2020") %>% select(Site, lon, lat, sampled) 


#Bind both dataframes 
Sites_NIFA<-rbind(site, TwentyTwentysites)
Sites_NIFA

#Convert lat/long data to epsg 5070 to match ecoregion projection in rgdal package
cords<-SpatialPoints(cbind(Sites_NIFA$lon, Sites_NIFA$lat), proj4string=CRS("+proj=longlat"))
coordscon<-spTransform(cords, CRS("+init=epsg:5070"))

#Transform to data frame and add site information 
convertdata<-data.frame(coordscon) %>% cbind(Sites_NIFA$Site) %>% 
  rename(Site="Sites_NIFA$Site") %>%
  rename(x="coords.x1") %>% 
  rename(y="coords.x2")
convertdata
convertdata<-convertdata %>% 
  select(Site, x, y)

#Convert to sf object to match with ecoregion 
site.sf <- st_as_sf(convertdata, coords=c("x", "y"), crs=5070) 


#Overlay gps points with ecoregion polygons to see which sites are in which ecoregions
PostDocsites_ecoregions<-point.in.poly(site.sf, ecoregions) %>% as.data.frame()
PostDocsites_ecoregions
```







